CREATE DATABASE BASE_DE_DATOS_1;
/*  NO SE PERMITE CREAR BASES DE DATOS EL NOMBRE DE LA BASE DE DATOS CON ESPACIOS, PERMITIDO EL USO DE GUION BAJO,
ESTA PERMITIDO EL USO DE CAMEL CASE, EL COMANDO DE CREACION DE BASE DE DATOS SE ESCRIBE EN MAYUSCULA */